openapi: 3.0.1
info:
  title: Copilot for Reseracher APIs
  description: An API to search literature through PubMed
  version: v1
servers:
  - url: ${{API_URL}}
    description: Production Server
paths:
  /Gene/Search:
    get:
      tags:
        - Gene
      summary: Retrieve gene or protein data
      description: This endpoint retrieves detailed information on gene or protein, based on user-specified queries. e.g. 'show me where to detect the gene BRCA1?' or 'Is BRCA2 expressed in neurons ?'. This endpoint triggers only when users asks about gene expression.
      operationId: SearchGene
      parameters:
        - name: Name
          in: query
          description: The name of the gene or protein to be searched. For example, "BRCA1" or "KNG1".
          required: true
          schema:
            type: string
            description: The name of the gene or protein to be searched. For example, "BRCA1" or "KNG1".
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }