openapi: 3.0.1
info:
  title: Copilot for Reseracher APIs
  description: An API to search literature through PubMed
  version: v1
servers:
  - url: https://7502c69eca89.ngrok.app
    description: Production Server
paths:
  /api/TextRewrite:
    get:
      tags:
        - TextRew
      summary: Rewrite
      description: This endpoint allows users to rewrite or adapt text for a specific journal
      operationId: TextRewrite
      parameters:
        - name: journalName
          in: query
          description: 'name of the life sience journal'
          required: true
          schema:
            type: string
            description: 'name of the life sience journal'
      responses:
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
     
components:
  schemas:
    TextRewriteQuery:
      type: object
      properties:
        journalName:
          type: string
          description: 'name of the life sience journal'
          nullable: true
        inputText:
          type: string
          description: 'text to rewrite or adapt'
          nullable: true
        journalType:
          $ref: '#/components/schemas/JournalType'
          description: 'type or journal. If review, the value is 0, otherwise the value is 1.'
      additionalProperties: false
    JournalType:
      enum:
        - 0
        - 1
      type: integer
      format: int32
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
